# Generated by Django 4.2.20 on 2025-06-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homologations', '0002_remove_homologationrule_property_map'),
        ('transforms', '0002_remove_transformationrule_field_and_more'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='description',
        ),
        migrations.RemoveField(
            model_name='work',
            name='property_homologation',
        ),
        migrations.AddField(
            model_name='work',
            name='transformations',
            field=models.ManyToManyField(blank=True, related_name='works', to='transforms.transformationrule'),
        ),
        migrations.AlterField(
            model_name='work',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='homologations',
            field=models.ManyToManyField(blank=True, related_name='works', to='homologations.homologationrule'),
        ),
        migrations.AlterField(
            model_name='work',
            name='mapping',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
