# Generated by Django 4.2.20 on 2025-06-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0003_alter_work_connection'),
        ('workExecution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExecutionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executions', models.ManyToManyField(related_name='execution_lists', to='workExecution.workexecution')),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='works.work')),
            ],
        ),
    ]
