# Generated by Django 4.2.20 on 2025-06-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workExecutionList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexecutionlist',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
