services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: pwcc_db
      POSTGRES_USER: pwcc_user
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6378:6379"
    restart: always

volumes:
  pgdata:
