version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: tropicfeel_db
      POSTGRES_USER: tropicfeel_user
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  celery:
    build: .
    command: celery -A orquestador worker -l info
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  celery-beat:
    build: .
    command: celery -A orquestador beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  pgdata:
