# Generated by Django 4.2.20 on 2025-06-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_remove_workflow_is_active_remove_workflow_works_and_more'),
        ('workExecutionList', '0002_alter_workexecutionlist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexecutionlist',
            name='work',
        ),
        migrations.AddField(
            model_name='workexecutionlist',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow'),
        ),
    ]
