# Generated by Django 4.2.20 on 2025-06-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0001_initial'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='works',
            field=models.ManyToManyField(related_name='workflows', to='works.work'),
        ),
    ]
