# Generated by Django 4.2.20 on 2025-06-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='works',
        ),
        migrations.AddField(
            model_name='workflow',
            name='steps',
            field=models.JSONField(blank=True, default=list, help_text='Lista ordenada de pasos con configuración'),
        ),
    ]
