# Generated by Django 4.2.20 on 2025-04-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('shopify', 'Shopify'), ('sftp', 'SFTP'), ('ftp', 'FTP'), ('rest', 'REST API'), ('graphql', 'GraphQL API'), ('netsuite', 'NetSuite'), ('restlet', 'RESTlet')], max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configuración generada dinámicamente')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
