# Generated by Django 4.2.20 on 2025-05-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamically generated configuration'),
        ),
    ]

# Generated by Django 4.2.20 on 2025-05-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamically generated configuration'),
        ),
    ]
