# Generated by Django 4.2.20 on 2025-05-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_alter_connection_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='type',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('sftp', 'SFTP'), ('ftp', 'FTP'), ('rest', 'REST API'), ('graphql', 'GraphQL API'), ('netsuite', 'NetSuite'), ('restlet', 'RESTlet'), ('postgresql', 'PostgreSQL')], max_length=20),
        ),
    ]
