# Generated by Django 4.2.20 on 2025-05-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_alter_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
