# Generated by Django 4.2.20 on 2025-06-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransformationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('field', models.CharField(help_text='Nombre del campo a transformar', max_length=100)),
                ('transform_type', models.CharField(help_text='Tipo: date_format, mapping, etc.', max_length=50)),
                ('config', models.JSONField(help_text="Configuración específica (sin incluir 'type')")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
