# Generated by Django 4.2.20 on 2025-06-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transforms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformationrule',
            name='field',
        ),
        migrations.AlterField(
            model_name='transformationrule',
            name='config',
            field=models.JSONField(help_text="Configuración: {'fields': {'field.path': value}}"),
        ),
        migrations.AlterField(
            model_name='transformationrule',
            name='transform_type',
            field=models.CharField(choices=[('set', 'Set (establece campos nuevos o sobrescribe existentes)'), ('put', 'Put (agrega en listas o crea estructuras si no existen)'), ('delete', 'Delete (elimina campos)')], help_text='Tipo de transformación: set, put o delete', max_length=20),
        ),
    ]
