# Generated by Django 4.2.20 on 2025-05-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomologationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('csv_file', models.FileField(upload_to='homologations/')),
                ('property_map', models.JSONField(help_text="JSON object to define which property(ies) should be mapped. Example: {'target': 'product_name'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
