# Generated by Django 4.2.20 on 2025-05-29 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homologations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homologationrule',
            name='property_map',
        ),
    ]
