# Generated by Django 4.2.20 on 2025-06-10 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0005_connection_is_active'),
        ('homologations', '0002_remove_homologationrule_property_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('operation_type', models.CharField(choices=[('origin', 'Origin (Data Source)'), ('destiny', 'Destiny (Data Target)'), ('transfer', 'Transfer'), ('data', 'Data')], max_length=10)),
                ('config', models.JSONField(blank=True, help_text='Opcional: configuración específica para la operación (filtros, reglas, transformación)', null=True)),
                ('mapping', models.JSONField(blank=True, help_text="Opcional: mapeo de campos de entrada → salida. Ej: {'user_id': 'id'}", null=True)),
                ('property_homologation', models.JSONField(blank=True, help_text="JSON object to define which property(ies) should be mapped. Example: {'target': 'product_name'}", null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connections.connection')),
                ('homologations', models.ManyToManyField(blank=True, help_text='Asignar múltiples reglas de homologación a esta operación', related_name='operations', to='homologations.homologationrule')),
            ],
        ),
    ]
