# Generated by Django 4.2.20 on 2025-06-17 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0005_connection_is_active'),
        ('works', '0003_alter_work_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connections.connection'),
        ),
    ]
